# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
matrix:
 allow_failures:
  - php: hhvm
  - php: nightly
  
install:
- composer install
